name       : tcp_wrappers
version    : '7.6'
release    : 2
source     :
    - ftp://ftp.porcupine.org/pub/security/tcp_wrappers_7.6-ipv6.4.tar.gz : 038a580b6497bab516a3e0dca59dfa2fe8cf3c0151bef45d57572fb756c2a64c
license    : MIT
component  : binary.compat
summary    : Binary Compatibility Library
description: |
    This package provides binary compatibility only. It is forbidden to build against it.
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
setup      : |
    %apply_patches
build      : |
    # Much inspiration/borrowing from Fedora. Thanks guys!
    LIB_MAJOR=0
    LIB_MINOR=7
    LIB_REL=6
    OPT_FLAGS="$CFLAGS"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        OPTFLAGS="$OPTFLAGS -m32"
    fi
    make RPM_OPT_FLAGS="$OPT_FLAGS -fPIC -DPIC -D_REENTRANT -DHAVE_STRERROR -DACLEXEC" LDFLAGS="$LDFLAGS" MAJOR=${LIB_MAJOR} MINOR=${LIB_MINOR} REL=${LIB_REL} linux
install    : |
    install -D -d -m 00755 $installdir/%libdir%/
    cp libwrap.so.* $installdir/%libdir%/.
    chmod 00755 $installdir/%libdir%/*.so*
